//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVC5.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int Id { get; set; }
        public int User { get; set; }
        public int Action { get; set; }
        public int Service { get; set; }
    
        public virtual Action Action1 { get; set; }
        public virtual Service Service1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
